build:
	clang++ -o main -Wall -Wextra -pedantic -ggdb3 -std=c++17 -fsanitize=address main.cpp -lSDL2 -lSDL2_image
stripped: stripped.cpp
	clang++ -o stripped -Wall -Wextra -pedantic -ggdb3 -std=c++17 -fsanitize=address stripped.cpp -lSDL2 -lSDL2_image
